import subprocess
import time
import sys
import http.server
import socketserver
import os

PORT = 8000
LOG_FILE = "app_crash.log"

print("🚀 LAUNCHING CRASH REPORTER...", file=sys.stderr)

# Start main.py with output redirected to file
# We use -u (unbuffered) to ensure logs are written immediately
with open(LOG_FILE, "w", encoding='utf-8') as f:
    proc = subprocess.Popen(
        ["python", "-u", "main.py"],
        stdout=f,
        stderr=subprocess.STDOUT
    )

# Wait a few seconds to see if it dies
time.sleep(5)

if proc.poll() is None:
    print("✅ App seems healthy (running > 5s). Streaming logs...", file=sys.stderr)
    # App is running. We need to keep this script alive and stream logs to stdout
    try:
        with open(LOG_FILE, "r", encoding='utf-8') as f:
            # Catch up to current end
            f.seek(0, 0) 
            while proc.poll() is None:
                line = f.readline()
                if line:
                    sys.stdout.write(line)
                    sys.stdout.flush()
                else:
                    time.sleep(0.5)
            # Dump remaining
            sys.stdout.write(f.read())
    except KeyboardInterrupt:
        proc.terminate()
        
    print(f"⚠️ App exited with code {proc.returncode}", file=sys.stderr)
else:
    print(f"❌ App died instantly with code {proc.returncode}", file=sys.stderr)

# If we are here, the app is dead.
# Check if we can bind to port 8000 (meaning app definitely let go of it)
try:
    # Prepare content
    with open(LOG_FILE, "r", encoding='utf-8') as f:
        log_content = f.read()

    html = f"""
    <html>
    <head>
        <title>Crash Report</title>
        <meta charset="utf-8">
    </head>
    <body style="font-family:monospace; background:#1e1e1e; color:#ff6b6b; padding:20px; line-height:1.5;">
        <h1 style="border-bottom: 2px solid #555; padding-bottom: 10px;">⚠️ Service Startup Failed</h1>
        <h2>Exit Code: {proc.returncode}</h2>
        <h3>Application Logs (Last 100 lines):</h3>
        <div style="background:#000; padding:15px; border:1px solid #444; white-space:pre-wrap; overflow-x:auto; border-radius: 5px;">
{log_content}
        </div>
        <p style="color: #888; margin-top: 20px;">Generated by Antigravity Crash Reporter</p>
    </body>
    </html>
    """

    class Handler(http.server.SimpleHTTPRequestHandler):
        def do_GET(self):
            self.send_response(500)
            self.send_header("Content-type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(html.encode("utf-8"))

    print("🚑 STARTING EMERGENCY HTTP SERVER...", file=sys.stderr)
    # Allow address reuse
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as httpd:
        httpd.serve_forever()

except Exception as e:
    print(f"❌ Failed to start emergency server: {e}", file=sys.stderr)
    # If fails, we just exit, and the container dies (which is fine, we tried)
    sys.exit(1)
