graph TD
    N0[__init__.py]
    N1[config_analyzer.py]
    N2[main.py]
    N3[demo_conflicts.py]
    N4[test_http_server.py]
    N5[__init__.py]
    N6[__init__.py]
    N7[__init__.py]
    N8[base.py]
    N9[claude.py]
    N10[gemini.py]
    N11[markdown.py]
    N12[openai.py]
    N13[ai_enhancer.py]
    N14[api_reference_builder.py]
    N15[architectural_pattern_detector.py]
    N16[code_analyzer.py]
    N17[codebase_scraper.py]
    N18[config_command.py]
    N19[config_enhancer.py]
    N20[config_extractor.py]
    N21[config_manager.py]
    N22[config_validator.py]
    N23[conflict_detector.py]
    N24[constants.py]
    N25[dependency_analyzer.py]
    N26[doc_scraper.py]
    N27[enhance_skill.py]
    N28[enhance_skill_local.py]
    N29[enhance_status.py]
    N30[estimate_pages.py]
    N31[generate_router.py]
    N32[github_fetcher.py]
    N33[github_scraper.py]
    N34[guide_enhancer.py]
    N35[how_to_guide_builder.py]
    N36[install_agent.py]
    N37[install_skill.py]
    N38[language_detector.py]
    N39[llms_txt_detector.py]
    N40[llms_txt_downloader.py]
    N41[llms_txt_parser.py]
    N42[main.py]
    N43[markdown_cleaner.py]
    N44[merge_sources.py]
    N45[package_multi.py]
    N46[package_skill.py]
    N47[pattern_recognizer.py]
    N48[pdf_extractor_poc.py]
    N49[pdf_scraper.py]
    N50[quality_checker.py]
    N51[rate_limit_handler.py]
    N52[resume_command.py]
    N53[run_tests.py]
    N54[setup_wizard.py]
    N55[split_config.py]
    N56[swift_patterns.py]
    N57[test_example_extractor.py]
    N58[test_unified_simple.py]
    N59[unified_codebase_analyzer.py]
    N60[unified_scraper.py]
    N61[unified_skill_builder.py]
    N62[upload_skill.py]
    N63[utils.py]
    N64[__init__.py]
    N65[agent_detector.py]
    N66[git_repo.py]
    N67[server.py]
    N68[server_fastmcp.py]
    N69[server_legacy.py]
    N70[source_manager.py]
    N71[__init__.py]
    N72[config_tools.py]
    N73[packaging_tools.py]
    N74[scraping_tools.py]
    N75[source_tools.py]
    N76[splitting_tools.py]
    N77[test_api.py]
    N78[__init__.py]
    N79[conftest.py]
    N80[__init__.py]
    N81[test_adaptors_e2e.py]
    N82[test_base.py]
    N83[test_claude_adaptor.py]
    N84[test_gemini_adaptor.py]
    N85[test_markdown_adaptor.py]
    N86[test_openai_adaptor.py]
    N87[test_api_reference_builder.py]
    N88[test_architecture_scenarios.py]
    N89[test_async_scraping.py]
    N90[test_bootstrap_skill.py]
    N91[test_bootstrap_skill_e2e.py]
    N92[test_c3_integration.py]
    N93[test_cli_paths.py]
    N94[test_code_analyzer.py]
    N95[test_codebase_scraper.py]
    N96[test_config_extractor.py]
    N97[test_config_validation.py]
    N98[test_constants.py]
    N99[test_dependency_analyzer.py]
    N100[test_e2e_three_stream_pipeline.py]
    N101[test_estimate_pages.py]
    N102[test_excluded_dirs_config.py]
    N103[test_generate_router_github.py]
    N104[test_git_repo.py]
    N105[test_git_sources_e2e.py]
    N106[test_github_fetcher.py]
    N107[test_github_scraper.py]
    N108[test_guide_enhancer.py]
    N109[test_how_to_guide_builder.py]
    N110[test_install_agent.py]
    N111[test_install_multiplatform.py]
    N112[test_install_skill.py]
    N113[test_install_skill_e2e.py]
    N114[test_integration.py]
    N115[test_issue_219_e2e.py]
    N116[test_language_detector.py]
    N117[test_llms_txt_detector.py]
    N118[test_llms_txt_downloader.py]
    N119[test_llms_txt_parser.py]
    N120[test_markdown_parsing.py]
    N121[test_mcp_fastmcp.py]
    N122[test_mcp_git_sources.py]
    N123[test_mcp_server.py]
    N124[test_merge_sources_github.py]
    N125[test_multi_source.py]
    N126[test_package_skill.py]
    N127[test_package_structure.py]
    N128[test_parallel_scraping.py]
    N129[test_pattern_recognizer.py]
    N130[test_pdf_advanced_features.py]
    N131[test_pdf_extractor.py]
    N132[test_pdf_scraper.py]
    N133[test_pr144_concerns.py]
    N134[test_quality_checker.py]
    N135[test_rate_limit_handler.py]
    N136[test_real_world_fastmcp.py]
    N137[test_scraper_features.py]
    N138[test_server_fastmcp_http.py]
    N139[test_setup_scripts.py]
    N140[test_skip_llms_txt.py]
    N141[test_smart_summarization.py]
    N142[test_source_manager.py]
    N143[test_swift_detection.py]
    N144[test_terminal_detection.py]
    N145[test_test_example_extractor.py]
    N146[test_unified.py]
    N147[test_unified_analyzer.py]
    N148[test_unified_mcp_integration.py]
    N149[test_upload_skill.py]
    N150[test_utilities.py]