"""add_module_type_to_reports

Revision ID: 403dfb0cfbd4
Revises: 20260331_merge_all_heads
Create Date: 2026-05-07 17:02:07.516486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403dfb0cfbd4'
down_revision = '20260331_merge_all_heads'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_titles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('fetched_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_page_titles_url'), ['url'], unique=True)

    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_type', sa.String(), nullable=True))

    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_saved_views_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_views_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_saved_views_team_id', 'teams', ['team_id'], ['id'])
        batch_op.create_foreign_key('fk_saved_views_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_saved_views_created_by', 'users', ['created_by'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('config')

    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.drop_column('module_type')

    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_saved_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_views_team_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('created_by')
        batch_op.drop_column('team_id')
        batch_op.drop_column('metrics')

    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.drop_column('module_type')

    with op.batch_alter_table('page_titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_titles_url'))
        batch_op.alter_column('fetched_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
