"""add_openrouter_api_key

Revision ID: 46c781526b51
Revises: 20260611_meta_andromeda_drift_reports
Create Date: 2026-06-17 14:09:30.059039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c781526b51'
down_revision = '20260611_meta_andromeda_drift_reports'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openrouter_api_key', sa.String(), nullable=True))

    # 資料遷移：將歷史資料中 ai_provider 為 gemini 的用戶改為 openrouter，並更新 ai_model 預設值
    op.execute("UPDATE users SET ai_provider = 'openrouter' WHERE ai_provider = 'gemini'")
    op.execute("UPDATE users SET ai_model = 'deepseek/deepseek-v4-flash' WHERE ai_model = 'gemini-1.5-flash'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('openrouter_api_key')
    # ### end Alembic commands ###
